#include <stdio.h>
#include <windows.h>

DECLSPEC_IMPORT void* MSVCRT$malloc(size_t);
DECLSPEC_IMPORT void* MSVCRT$realloc(void*, size_t);
DECLSPEC_IMPORT size_t MSVCRT$strlen(const char*);
DECLSPEC_IMPORT long MSVCRT$strtol(const char*, char**, int);
DECLSPEC_IMPORT unsigned long long MSVCRT$strtoull(const char*, char**, int);
DECLSPEC_IMPORT int MSVCRT$sprintf_s(char*, size_t, const char*, ...);

DECLSPEC_IMPORT errno_t MSVCRT$fopen_s(FILE**, const char*, const char*);
DECLSPEC_IMPORT int MSVCRT$_fseeki64(FILE*, __int64, int);
DECLSPEC_IMPORT size_t MSVCRT$fread(void*, size_t, size_t, FILE*);
DECLSPEC_IMPORT size_t MSVCRT$fwrite(const void*, size_t, size_t, FILE*);
DECLSPEC_IMPORT int MSVCRT$fclose(FILE*);

DECLSPEC_IMPORT int MSVCRT$rename(const char*, const char*);
DECLSPEC_IMPORT int MSVCRT$remove(const char*);

WINBASEAPI BOOL WINAPI Kernel32$CloseHandle(HANDLE);
WINBASEAPI BOOL WINAPI Kernel32$CreateProcessA(LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES, BOOL, DWORD, LPVOID, LPCSTR, LPSTARTUPINFOA, LPPROCESS_INFORMATION);
WINBASEAPI BOOL WINAPI Kernel32$CreatePipe(PHANDLE, PHANDLE, LPSECURITY_ATTRIBUTES, DWORD);

WINBASEAPI BOOL WINAPI Kernel32$ReadFile(HANDLE, LPVOID, DWORD, LPDWORD, LPOVERLAPPED);
WINBASEAPI HANDLE WINAPI Kernel32$FindFirstFileA(LPCSTR, LPWIN32_FIND_DATAA);
WINBASEAPI BOOL WINAPI Kernel32$FindNextFileA(HANDLE, LPWIN32_FIND_DATAA);
WINBASEAPI BOOL WINAPI Kernel32$FindClose(HANDLE);
WINBASEAPI DWORD WINAPI Kernel32$GetFullPathNameA(LPCSTR, DWORD, LPSTR, LPSTR*);
WINBASEAPI BOOL WINAPI Kernel32$FileTimeToLocalFileTime(const FILETIME*, LPFILETIME);
WINBASEAPI BOOL WINAPI Kernel32$FileTimeToSystemTime(FILETIME*, LPSYSTEMTIME);
WINBASEAPI BOOL WINAPI Kernel32$CopyFileA(LPCSTR, LPCSTR, BOOL);
WINBASEAPI BOOL WINAPI Kernel32$CreateDirectoryA(LPCSTR, LPSECURITY_ATTRIBUTES);

WINBASEAPI int WINAPI User32$MessageBoxA(HWND, LPCSTR, LPCSTR, UINT);